Don't use fully qualified path for sdkmanager after setup-android

diff --git a/.github/workflows/PullRequestWorkflow.yaml b/.github/workflows/PullRequestWorkflow.yaml
--- a/.github/workflows/PullRequestWorkflow.yaml
+++ b/.github/workflows/PullRequestWorkflow.yaml
@@ -125,17 +125,14 @@ jobs:
 
       - name: Install Emulator
         run: |
-          yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --install "${{ matrix.device.img }}"
-
-      - name: Accept licenses
-        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true
+          yes | sdkmanager --install "${{ matrix.device.img }}"
 
       - name: Log Emulator Version
         run: |
           echo "Emulator source.properties:"
           cat $ANDROID_HOME/emulator/source.properties || echo "emulator/source.properties not found"
           echo "SDK Manager on $ANDROID_HOME"
-          ls -l $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager && $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --version || echo "sdkmanager not found"
+          ls -l sdkmanager && sdkmanager --version || echo "sdkmanager not found"
 
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v4
