Use SDK from android-actions/setup-android

diff --git a/.github/workflows/PullRequestWorkflow.yaml b/.github/workflows/PullRequestWorkflow.yaml
--- a/.github/workflows/PullRequestWorkflow.yaml
+++ b/.github/workflows/PullRequestWorkflow.yaml
@@ -108,6 +108,12 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
+      - name: Enable KVM group perms
+        run: |
+          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
+          sudo udevadm control --reload-rules
+          sudo udevadm trigger --name-match=kvm
+
       - name: Set up JDK
         uses: actions/setup-java@v5
         with:
@@ -117,31 +123,19 @@ jobs:
       - name: Set up Android SDK
         uses: android-actions/setup-android@v3
 
-      - name: Downgrade/Install specific cmdline-tools version
-        run: |
-          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "cmdline-tools;9.0"
-          echo "$ANDROID_HOME/cmdline-tools/9.0/bin" >> $GITHUB_PATH
-
-      - name: Verify cmdline-tools version
-        run: $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --version
-
-      - name: Log Emulator Version
-        run: |
-          echo "Emulator source.properties:"
-          cat $ANDROID_HOME/emulator/source.properties || echo "emulator/source.properties not found"
-
-      - name: Enable KVM group perms
-        run: |
-          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
-          sudo udevadm control --reload-rules
-          sudo udevadm trigger --name-match=kvm
-
       - name: Install Emulator
         run: |
           yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --install "${{ matrix.device.img }}"
 
       - name: Accept licenses
         run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true
+
+      - name: Log Emulator Version
+        run: |
+          echo "Emulator source.properties:"
+          cat $ANDROID_HOME/emulator/source.properties || echo "emulator/source.properties not found"
+          echo "SDK Manager on $ANDROID_HOME"
+          ls -l $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager && $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --version || echo "sdkmanager not found"
 
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v4
